In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from zebrafish_ms2_paper.utils import colors, pboc_rc, style_axes

In [28]:
fontsize = 11
linewidth = 2
markersize = 4
rcParams.update(pboc_rc)
rcParams['pdf.fonttype'] = 42

In [31]:
%matplotlib qt

In [2]:
df = pd.read_pickle(r'/home/brandon/Downloads/SupplementalDataFiles/Supplemental_Data_File_1-Spots.pkl')

In [9]:
spots_per_nucleus = []
for t in df.t.unique():
    sub_df = df[df.t== t]
    sub_df.groupby('nucleus_id').apply(lambda x: len(x))
    spots_per_nucleus.extend(sub_df.groupby('nucleus_id').apply(lambda x: len(x)).values)

In [21]:
bins = np.arange(1, np.max(spots_per_nucleus))
counts, bins = np.histogram(spots_per_nucleus, bins)
probs = counts / np.sum(counts)


In [41]:
refined_bins = np.array([1, 2, 3])
refined_probs = np.zeros(3)
refined_probs[0] = probs[0]
refined_probs[1] = probs[1]
refined_probs[2] = np.sum(probs[2:])
print(refined_probs)

plt.figure(figsize=[3.5, 3.5])
plt.bar(refined_bins, refined_probs, color=colors['green'])
plt.xticks([1, 2, 3], labels=['1', '2', '3+'])
plt.xlabel('number of spots per nucleus', fontsize=fontsize)
plt.ylabel('fraction of nuclei', fontsize=fontsize)
ax = style_axes(plt.gca(), fontsize=fontsize)
plt.tight_layout()

[0.95692072 0.03823604 0.00484323]


In [42]:
plt.savefig(r'/home/brandon/Documents/Code/zebrafish-ms2-paper/figures/spots_per_nucleus_fig.pdf')

In [14]:
bins

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
counts

array([   0, 7508,  300,   31,    5,    2])

In [38]:
plt.gcf().get_size_inches()

array([3.46666667, 3.29333333])

In [37]:
plt.tight_layout()